# ceramic.yaml
# 按照network spec中的定义配置
---
apiVersion: "keramik.3box.io/v1alpha1"
kind: Network
metadata:
  name: ceramic
spec:
  replicas: 1
  namespace: ns-1
  networkType: testnet-clay # mainnet
  ceramic:
    - ceramicPostgres:
        dbName: db_ceramic
        userName: user_ceramic
        password: pw_123456_ceramic